# Atom Project Build Configuration
# This file defines build presets and configuration options

version: "1.0"
project:
  name: "Atom"
  version: "1.0.0"
  description: "Foundational library for astronomical software"

# Build presets for common configurations
presets:
  debug:
    build_type: "debug"
    options:
      - "--tests"
      - "--examples"
      - "--sanitizers"
    description: "Debug build with tests and sanitizers"
  
  release:
    build_type: "release"
    options:
      - "--lto"
    description: "Optimized release build"
  
  dev:
    build_type: "relwithdebinfo"
    options:
      - "--tests"
      - "--examples"
      - "--docs"
      - "--ccache"
    description: "Development build with debug info"
  
  python:
    build_type: "release"
    options:
      - "--python"
      - "--shared"
    description: "Python bindings build"
  
  minimal:
    build_type: "minsizerel"
    options: []
    description: "Minimal size build"
  
  full:
    build_type: "release"
    options:
      - "--python"
      - "--examples"
      - "--tests"
      - "--docs"
      - "--cfitsio"
      - "--ssh"
      - "--shared"
    description: "Full feature build"

# Compiler configurations
compilers:
  gcc:
    min_version: "10.0"
    recommended_flags:
      debug: ["-g", "-O0", "-Wall", "-Wextra"]
      release: ["-O3", "-DNDEBUG", "-march=native"]
  
  clang:
    min_version: "10.0"
    recommended_flags:
      debug: ["-g", "-O0", "-Wall", "-Wextra"]
      release: ["-O3", "-DNDEBUG", "-march=native"]
  
  msvc:
    min_version: "19.28"
    recommended_flags:
      debug: ["/Od", "/Wall"]
      release: ["/O2", "/DNDEBUG"]

# Platform-specific settings
platforms:
  linux:
    preferred_generator: "Ninja"
    package_manager: "vcpkg"
    
  windows:
    preferred_generator: "Visual Studio 17 2022"
    package_manager: "vcpkg"
    
  macos:
    preferred_generator: "Ninja"
    package_manager: "vcpkg"

# Dependencies configuration
dependencies:
  required:
    - name: "fmt"
      version: ">=9.0.0"
    - name: "asio"
      version: ">=1.24.0"
    - name: "zlib"
      version: ">=1.2.11"
  
  optional:
    - name: "cfitsio"
      condition: "ATOM_USE_CFITSIO"
    - name: "libssh"
      condition: "ATOM_USE_SSH"
    - name: "pybind11"
      condition: "ATOM_BUILD_PYTHON_BINDINGS"

# Build optimization settings
optimization:
  lto:
    supported_compilers: ["gcc", "clang", "msvc"]
    min_cmake_version: "3.9"
  
  ccache:
    supported_platforms: ["linux", "macos", "windows"]
    max_cache_size: "5G"
  
  parallel_build:
    auto_detect_cores: true
    memory_per_job_gb: 2
    max_jobs: 16
